### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by fxleblanc** [Kilobyte22/lockd#3]
- http://pastebin.com/gL3kmreu
- Rustc version: 1.4.0-nightly (fe9cef7da 2015-08-30)

**Comment by dequbed** [comment]
Given the rapid change in the rust ecosystem it would be a very big undertaking supporting more than just the current version of rustc and rustc nightly. Please update to the latest version of rustc (currently 1.8.0 or 1.9.0-nightly).

**Comment by fxleblanc** [comment]
works with 1.10.0. Thanks for your help. Nice program btw.
